#!/bin/sh

echo "Starting OpenVPN"

# Create OpenVPN files
mkdir -p /dev/net
mknod /dev/net/tun c 10 200

echo -e "$VPN_USER\n$VPN_PASS" > /surfshark/credentials.conf

export HTTP_PROXY=socks5h://127.0.0.1:8118
export HTTPS_PROXY=socks5h://127.0.0.1:8118

# Openvpn scripts can't access the environment variables, so save them to a file
echo "PRIVATE_NET=$PRIVATE_NET" > /env

/sbin/ip -o -4 route show to default > /default_route

# Start openvpn
timeout 18h openvpn \
  --config "$VPN_FILE" \
  --script-security 2 \
  --route-delay 1 \
  --up-restart \
  --ping 10 \
  --ping-restart 10 \
  --persist-tun \
  --auth-user-pass /surfshark/credentials.conf
